Moved Dummy class into a subdirectory. I'd expect it to work, but it throws a compilation error.
Error dump says:
ketch\testFileSeparation.ino.cpp.o:(.text.setup+0xc): undefined reference to `Dummy::Dummy()'

sketch\testFileSeparation.ino.cpp.o: In function `HardwareSerial::begin(unsigned long)':

C:\Users\mlewand\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:75: undefined reference to `Dummy::Dummy()'

sketch\testFileSeparation.ino.cpp.o: In function `setup':

c:\dev\workspace\tmp\arduino\wittymini\testFileSeparation/testFileSeparation.ino:9: undefined reference to `Dummy::print()'

sketch\testFileSeparation.ino.cpp.o: In function `loop':

c:\dev\workspace\tmp\arduino\wittymini\testFileSeparation/testFileSeparation.ino:11: undefined reference to `Dummy::print()'

collect2.exe: error: ld returned 1 exit status

exit status 1
[Error] Exit with code=1